# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_xbar_7/config_mpsoc_xbar_7.xci
# IP: The module: 'config_mpsoc_xbar_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.gen/sources_1/bd/config_mpsoc/ip/config_mpsoc_xbar_7/config_mpsoc_xbar_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_xbar_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.srcs/sources_1/bd/config_mpsoc/ip/config_mpsoc_xbar_7/config_mpsoc_xbar_7.xci
# IP: The module: 'config_mpsoc_xbar_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.gen/sources_1/bd/config_mpsoc/ip/config_mpsoc_xbar_7/config_mpsoc_xbar_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_mpsoc_xbar_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
