set_property SRC_FILE_INFO {cfile:C:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.srcs/constrs_1/imports/Documents/U55C_xdc_1v00.xdc rfile:../../../ZCU_104_SPAR.srcs/constrs_1/imports/Documents/U55C_xdc_1v00.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BP47 [get_ports fpga_uart0_rxd]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BN47 [get_ports fpga_uart0_txd]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BK44 [get_ports refclk_clk_n]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BM8 [get_ports reset_rtl]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports uart2_pl_txd]
