# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Documents/U55C_xdc_1v00.xdc

# Block Designs: bd/config_mpsoc/config_mpsoc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc || ORIG_REF_NAME==config_mpsoc} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_mySPAR_v1_0_0/config_mpsoc_mySPAR_v1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_mySPAR_v1_0_0 || ORIG_REF_NAME==config_mpsoc_mySPAR_v1_0_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_microblaze_0_1/config_mpsoc_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_microblaze_0_1 || ORIG_REF_NAME==config_mpsoc_microblaze_0_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_dlmb_v10_1/config_mpsoc_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_dlmb_v10_1 || ORIG_REF_NAME==config_mpsoc_dlmb_v10_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_ilmb_v10_1/config_mpsoc_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_ilmb_v10_1 || ORIG_REF_NAME==config_mpsoc_ilmb_v10_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_dlmb_bram_if_cntlr_1/config_mpsoc_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==config_mpsoc_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_ilmb_bram_if_cntlr_1/config_mpsoc_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==config_mpsoc_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_lmb_bram_1/config_mpsoc_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_lmb_bram_1 || ORIG_REF_NAME==config_mpsoc_lmb_bram_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_xbar_7/config_mpsoc_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_xbar_7 || ORIG_REF_NAME==config_mpsoc_xbar_7} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_microblaze_0_axi_periph_4/config_mpsoc_microblaze_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_microblaze_0_axi_periph_4 || ORIG_REF_NAME==config_mpsoc_microblaze_0_axi_periph_4} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_microblaze_0_axi_intc_0/config_mpsoc_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_microblaze_0_axi_intc_0 || ORIG_REF_NAME==config_mpsoc_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_microblaze_0_xlconcat_0/config_mpsoc_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_microblaze_0_xlconcat_0 || ORIG_REF_NAME==config_mpsoc_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_mdm_1_1/config_mpsoc_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_mdm_1_1 || ORIG_REF_NAME==config_mpsoc_mdm_1_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_axi_uartlite_0_0/config_mpsoc_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_axi_uartlite_0_0 || ORIG_REF_NAME==config_mpsoc_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_clk_wiz_1_1/config_mpsoc_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_clk_wiz_1_1 || ORIG_REF_NAME==config_mpsoc_clk_wiz_1_1} -quiet] -quiet

# IP: bd/config_mpsoc/ip/config_mpsoc_rst_clk_wiz_1_100M_1/config_mpsoc_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==config_mpsoc_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==config_mpsoc_rst_clk_wiz_1_100M_1} -quiet] -quiet

# XDC: c:/Users/Njfre/Downloads/U55C_SPAR.xpr/U55C_SPAR_Ready/ZCU_104_SPAR/ZCU_104_SPAR.gen/sources_1/bd/config_mpsoc/config_mpsoc_ooc.xdc
